#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
awk '{if($1=="127.0.0.1" && $2=="localhost") print "127.0.0.2 localhost"; else print}' /etc/hosts > /tmp/newhosts && cat /tmp/newhosts > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
